/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.GabaldonPolMartinezMarti.vista;

import java.awt.Dimension;
import java.io.File;
import java.awt.Toolkit;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import ub.info.prog2.GabaldonPolMartinezMarti.controlador.Controlador;
import ub.info.prog2.GabaldonPolMartinezMarti.model.FitxerMultimedia;
import ub.info.prog2.utils.ReproException;
import javax.swing.JOptionPane;
import java.util.Iterator;
import javax.swing.JFileChooser;
import javax.swing.ListSelectionModel;
/**
 *
 * @author polg24
 */
public class AplicacioUB4 extends javax.swing.JFrame {

    private Controlador controlador;
    /**
     * Creates new form AplicacioUB4
     */
    public AplicacioUB4() {
        initComponents();
        controlador = new Controlador();
        btnCrearPortafoli.setEnabled(false);
        btnEliminarPortafoli.setEnabled(false);
        btnEliminarFitxerRepositori.setEnabled(false);
        btnAfegirFitxerPortafoli.setEnabled(false);
        btnPlayFitxerRepositori.setEnabled(false);
        btnPlayRepositori.setEnabled(false);
        btnPlayPortafoli.setEnabled(false);
        btnEliminarFitxerPortafoli.setEnabled(false);
        lstRepositori.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setPreferredSize(new Dimension(screenSize.width * 7 / 8, screenSize.height * 7/8));
    }
    
    private void updateCmbPortafolis() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        Iterator<String> iter = controlador.getTitolsPortafolis().iterator();
        while (iter.hasNext()) {
            model.addElement(iter.next());
        }
        cmbPortafolis.setModel(model);
        updateBtnAfegirFitxerPortafoli();
        updateLstPortafoli();
    }
    
    private void updateEliminarPortafoli() {
        btnEliminarPortafoli.setEnabled(controlador.getSizePortafolis() != 0);
    }
    
    private void updateBtnEliminarFitxerRepositori() {
        btnEliminarFitxerRepositori.setEnabled(!lstRepositori.isSelectionEmpty());
    }
    
    private void updateBtnEliminarFitxerPortafoli(){
        btnEliminarFitxerPortafoli.setEnabled(!lstPortafoli.isSelectionEmpty());
    }
    
    private void updateBtnAfegirFitxerPortafoli() {
        btnAfegirFitxerPortafoli.setEnabled(!lstRepositori.isSelectionEmpty() && cmbPortafolis.getItemCount() != 0);
    }
    
    private void updateLstRepositori() {
        DefaultListModel<String> model = new DefaultListModel<>();
        int size = controlador.getSizeRepositori();
        for (int i = 0; i < size; i++) {
            model.addElement(((FitxerMultimedia)controlador.getAtRepositori(i)).resum());
        }
        lstRepositori.setModel(model);
    }
    
    private void updateLstPortafoli() {
        DefaultListModel<String> model = new DefaultListModel<>();
        int size = controlador.getSizePortafoli((String)cmbPortafolis.getSelectedItem());
        for (int i = 0; i < size; i++) {
            model.addElement(((FitxerMultimedia)controlador.getAtPortafoli((String)cmbPortafolis.getSelectedItem(), i)).resum());
        }
        lstPortafoli.setModel(model);
    }
    
    private void updateBtnPlayFitxerRepositori(){
        btnPlayFitxerRepositori.setEnabled(!lstRepositori.isSelectionEmpty());
    }
    
    private void updateBtnPlayPortafoli(){
        btnPlayPortafoli.setEnabled(controlador.getSizePortafolis() != 0);
        
    }
    
    private void updateBtnPlayRepositori(){
        btnPlayRepositori.setEnabled(controlador.getSizeRepositori()!= 0);
    }
    
    private void updateChkCiclica(){
        chkCiclica.setSelected(controlador.getCiclica());
    }
    
    private void updateChkReverse(){
        chkReverse.setSelected(controlador.getReverse());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAfegirFitxerRepositori = new javax.swing.JButton();
        btnEliminarFitxerRepositori = new javax.swing.JButton();
        btnCrearPortafoli = new javax.swing.JButton();
        btnEliminarPortafoli = new javax.swing.JButton();
        btnAfegirFitxerPortafoli = new javax.swing.JButton();
        btnEliminarFitxerPortafoli = new javax.swing.JButton();
        btnPlayFitxerRepositori = new javax.swing.JButton();
        btnPlayPortafoli = new javax.swing.JButton();
        btnPlayRepositori = new javax.swing.JButton();
        chkCiclica = new javax.swing.JCheckBox();
        chkReverse = new javax.swing.JCheckBox();
        btnPlay = new javax.swing.JButton();
        btnPause = new javax.swing.JButton();
        btnAtura = new javax.swing.JButton();
        btnSalta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstRepositori = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPortafoli = new javax.swing.JList<>();
        cmbPortafolis = new javax.swing.JComboBox<>();
        txtTitolPortafoli = new javax.swing.JTextField();
        lblTitolPortafoli = new javax.swing.JLabel();
        lblSeleccionarPortafoli = new javax.swing.JLabel();
        btnRecuperaDades = new javax.swing.JButton();
        btnGuardaDades = new javax.swing.JButton();
        btnMarti = new javax.swing.JButton();
        btnPol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 241, 241));

        btnAfegirFitxerRepositori.setText("Afegir un Fitxer al Repositori");
        btnAfegirFitxerRepositori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerRepositoriActionPerformed(evt);
            }
        });

        btnEliminarFitxerRepositori.setText("Eliminar Fitxer seleccionat del Repositori");
        btnEliminarFitxerRepositori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFitxerRepositoriActionPerformed(evt);
            }
        });

        btnCrearPortafoli.setText("Crear Portafoli");
        btnCrearPortafoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPortafoliActionPerformed(evt);
            }
        });

        btnEliminarPortafoli.setText("Eliminar Portafoli");
        btnEliminarPortafoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPortafoliActionPerformed(evt);
            }
        });

        btnAfegirFitxerPortafoli.setText("Afegir un Fitxer al Portafoli seleccionat");
        btnAfegirFitxerPortafoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirFitxerPortafoliActionPerformed(evt);
            }
        });

        btnEliminarFitxerPortafoli.setText("Eliminar Fitxer seleccionat d'un Portafoli");
        btnEliminarFitxerPortafoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFitxerPortafoliActionPerformed(evt);
            }
        });

        btnPlayFitxerRepositori.setText("Reproduir el Fitxer seleccionat del Repositori");
        btnPlayFitxerRepositori.setToolTipText("");
        btnPlayFitxerRepositori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayFitxerRepositoriActionPerformed(evt);
            }
        });

        btnPlayPortafoli.setText("Reproduir el Portafoli seleccionat");
        btnPlayPortafoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayPortafoliActionPerformed(evt);
            }
        });

        btnPlayRepositori.setText("Reproduir el Repositori");
        btnPlayRepositori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayRepositoriActionPerformed(evt);
            }
        });

        chkCiclica.setText("Reproduccio Cíclica");
        chkCiclica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCiclicaActionPerformed(evt);
            }
        });

        chkReverse.setText("Reproduccio Reverse");
        chkReverse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkReverseActionPerformed(evt);
            }
        });

        btnPlay.setText("Play");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        btnPause.setText("Pause");
        btnPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseActionPerformed(evt);
            }
        });

        btnAtura.setText("Atura");
        btnAtura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAturaActionPerformed(evt);
            }
        });

        btnSalta.setText("Salta");
        btnSalta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaltaActionPerformed(evt);
            }
        });

        lstRepositori.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lstRepositoriComponentAdded(evt);
            }
        });
        lstRepositori.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRepositoriValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstRepositori);

        lstPortafoli.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPortafoliValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPortafoli);

        cmbPortafolis.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPortafolisItemStateChanged(evt);
            }
        });

        txtTitolPortafoli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTitolPortafoliKeyReleased(evt);
            }
        });

        lblTitolPortafoli.setText("Títol Portafoli:");

        lblSeleccionarPortafoli.setText("Seleccionar Portafoli:");

        btnRecuperaDades.setText("Recupera dades des d'un fitxer");
        btnRecuperaDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperaDadesActionPerformed(evt);
            }
        });

        btnGuardaDades.setText("Guarda dades a un fitxer");
        btnGuardaDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaDadesActionPerformed(evt);
            }
        });

        btnMarti.setText("Boto Marti");
        btnMarti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMartiActionPerformed(evt);
            }
        });

        btnPol.setText("Boto Pol");
        btnPol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnEliminarFitxerRepositori)
                                    .addComponent(btnEliminarFitxerPortafoli)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnRecuperaDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnGuardaDades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnPlayPortafoli)
                                            .addComponent(btnPlayFitxerRepositori)
                                            .addComponent(btnPlayRepositori)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(160, 160, 160)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnPol)
                                            .addComponent(btnMarti)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAfegirFitxerPortafoli)
                                    .addComponent(btnAfegirFitxerRepositori))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCrearPortafoli, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addComponent(txtTitolPortafoli))
                                    .addComponent(lblTitolPortafoli)
                                    .addComponent(btnEliminarPortafoli))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeleccionarPortafoli)
                                    .addComponent(cmbPortafolis, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(360, 360, 360)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkReverse)
                                    .addComponent(chkCiclica)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPlay)
                                .addGap(27, 27, 27)
                                .addComponent(btnPause)
                                .addGap(55, 55, 55)
                                .addComponent(btnAtura)
                                .addGap(31, 31, 31)
                                .addComponent(btnSalta)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(lblTitolPortafoli))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSeleccionarPortafoli)))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitolPortafoli)
                            .addComponent(btnAfegirFitxerRepositori)
                            .addComponent(cmbPortafolis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAfegirFitxerPortafoli)
                            .addComponent(btnCrearPortafoli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarPortafoli)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(btnEliminarFitxerRepositori)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarFitxerPortafoli))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(btnMarti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPol)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlayFitxerRepositori)
                            .addComponent(btnRecuperaDades))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlayRepositori)
                            .addComponent(btnGuardaDades))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlayPortafoli)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(chkCiclica)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPlay)
                            .addComponent(btnPause)
                            .addComponent(btnAtura)
                            .addComponent(btnSalta))
                        .addGap(12, 12, 12))
                    .addComponent(chkReverse))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTitolPortafoliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTitolPortafoliKeyReleased
        btnCrearPortafoli.setEnabled(!txtTitolPortafoli.getText().equals(""));
    }//GEN-LAST:event_txtTitolPortafoliKeyReleased

    private void btnCrearPortafoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPortafoliActionPerformed
        try {
            controlador.addPortafoli(txtTitolPortafoli.getText());
            txtTitolPortafoli.setText("");
            btnCrearPortafoli.setEnabled(false);
            updateCmbPortafolis();
            updateEliminarPortafoli();
            updateBtnPlayPortafoli();
            updateLstPortafoli();
            
        }
        catch (ReproException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Error al crear Portafoli", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearPortafoliActionPerformed

    private void btnEliminarPortafoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPortafoliActionPerformed
        try {                                                  
            controlador.removePortafoli((String)cmbPortafolis.getSelectedItem());
            updateCmbPortafolis();
            updateEliminarPortafoli();
            updateBtnPlayPortafoli();
            updateLstPortafoli();
        }
        catch (ReproException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Error a l'eliminar Portafoli", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarPortafoliActionPerformed

    private void btnAfegirFitxerRepositoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerRepositoriActionPerformed
        FrmAfegirFitxerMultimedia2 jDAfegir = new FrmAfegirFitxerMultimedia2(this, true, controlador);
        
        jDAfegir.setTitle("Afegir Fitxer Multimedia");
        
        jDAfegir.pack();
        jDAfegir.setVisible(true);
        
        updateLstRepositori();
        updateBtnPlayRepositori();

    }//GEN-LAST:event_btnAfegirFitxerRepositoriActionPerformed

    private void btnEliminarFitxerRepositoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFitxerRepositoriActionPerformed
        try {
            controlador.removeFitxer(lstRepositori.getSelectedIndex());
        }
        catch (ReproException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Error a l'eliminar Portafoli", JOptionPane.ERROR_MESSAGE);
        }

        updateLstRepositori();
        updateLstPortafoli();
        updateBtnPlayRepositori();

    }//GEN-LAST:event_btnEliminarFitxerRepositoriActionPerformed

    private void lstRepositoriValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRepositoriValueChanged
        updateBtnEliminarFitxerRepositori();
        updateBtnPlayFitxerRepositori();
        updateBtnAfegirFitxerPortafoli();
    }//GEN-LAST:event_lstRepositoriValueChanged

    private void btnAfegirFitxerPortafoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirFitxerPortafoliActionPerformed
        try {
            controlador.addFitxer((String)cmbPortafolis.getSelectedItem(), lstRepositori.getSelectedIndex() + 1);
        }
        catch (ReproException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Error a l'afegir un fitxer a un Portafoli", JOptionPane.ERROR_MESSAGE);
        }
        updateLstPortafoli();
    }//GEN-LAST:event_btnAfegirFitxerPortafoliActionPerformed

    private void btnGuardaDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaDadesActionPerformed
        // TODO add your handling code here:
        File fitxer;
        //Creació del selector de fitxer
        JFileChooser seleccio = new JFileChooser();
        //Mostrem la finestra de dialeg
        //Resultat emmagazema una constant que indica si s’ha
        //seleccionat o no un fitxer
        int resultat = seleccio.showOpenDialog(this);
        //Assegurem que hi hagi un fitxer seleccionat
        if (resultat == JFileChooser.APPROVE_OPTION) {
            fitxer=seleccio.getSelectedFile();
        
            try{
                controlador.saveDades(fitxer.toString());
                JOptionPane.showMessageDialog(this, "Llista guardada exitosament");

            }
            catch(ReproException e){
                JOptionPane.showMessageDialog(this, e.toString(), "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
            }
        }
    }//GEN-LAST:event_btnGuardaDadesActionPerformed

    private void btnRecuperaDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperaDadesActionPerformed
        // TODO add your handling code here:
        File fitxer;
        //Creació del selector de fitxer
        JFileChooser seleccio = new JFileChooser();
        //Mostrem la finestra de dialeg
        //Resultat emmagazema una constant que indica si s’ha
        //seleccionat o no un fitxer
        int resultat = seleccio.showOpenDialog(this);
        //Assegurem que hi hagi un fitxer seleccionat
        if (resultat == JFileChooser.APPROVE_OPTION) {
            fitxer=seleccio.getSelectedFile();
        
            try{
                controlador.loadDades(fitxer.toString());
                updateLstRepositori();
                updateCmbPortafolis();
                updateLstPortafoli();                        
                updateEliminarPortafoli();
                updateBtnPlayPortafoli();
                updateBtnEliminarFitxerRepositori();
                updateBtnEliminarFitxerPortafoli();
                updateBtnAfegirFitxerPortafoli();
                updateBtnPlayRepositori();
                updateChkCiclica();
                updateChkReverse();
                
                JOptionPane.showMessageDialog(this, "Llista recuperada exitosament");
                

            }
            catch(ReproException e){
                JOptionPane.showMessageDialog(this, e.toString(), "Error al recuperar", JOptionPane.ERROR_MESSAGE);
                
            }
        }  
    }//GEN-LAST:event_btnRecuperaDadesActionPerformed

    private void btnMartiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMartiActionPerformed
        try {
            controlador.addImatge("C:\\Users\\marti\\Desktop\\Reproductor\\5e88a0ba2500003903058a57.jpeg", "Bad Bunny", ".jpeg", 1, 2);
            controlador.addImatge("C:\\Users\\marti\\Desktop\\Reproductor\\1661714716010501_c5_720x720.jpeg", "Angels", ".png", 1, 2);
            controlador.addImatge("C:\\Users\\marti\\Desktop\\Reproductor\\descarga.jpg", "C Tangana", ".png", 1, 2);
            controlador.addAudio("C:\\Users\\marti\\Desktop\\Reproductor\\Bad Bunny - A Tu Merced (Letra ) (1).mp3", "C:\\Users\\marti\\Desktop\\Reproductor\\5e88a0ba2500003903058a57.jpeg", "Bad Bunny", "08642", 45678);
            controlador.addAudio("C:\\Users\\marti\\Desktop\\Reproductor\\C. Tangana - Antes de morirme feat. Rosalía (Video Oficial).mp3", "C:\\Users\\marti\\Desktop\\Reproductor\\descarga.jpg", "C Tangana", "08642", 45678);
            controlador.addAudio("C:\\Users\\marti\\Desktop\\Reproductor\\C. Tangana - De Pie (Audio) (GOEAR.ORG).mp3", "C:\\Users\\marti\\Desktop\\Reproductor\\descarga.jpg", "C Tangana", "08642", 45678);
            controlador.addAudio("C:\\Users\\marti\\Desktop\\Reproductor\\C. Tangana - Llorando en la Limo (Video Oficial).mp3", "C:\\Users\\marti\\Desktop\\Reproductor\\descarga.jpg", "C Tangana", "08642", 45678);
            controlador.addAudio("C:\\Users\\marti\\Desktop\\Reproductor\\James Blake - Barefoot In The Park (feat. Rosalía).mp3", "C:\\Users\\marti\\Desktop\\Reproductor\\James_Blake_630.jpg", "Rosalia", "08642", 45678);
            controlador.addAudio("C:\\Users\\marti\\Desktop\\Reproductor\\Yves_Tumor_-_Gospel_For_A_New_Centurycom.mp3", "C:\\Users\\marti\\Desktop\\Reproductor\\James_Blake_630.jpg", "Yves", "08642", 45678);
            updateLstRepositori();
            updateBtnPlayRepositori();

        }
        catch (ReproException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Error a l'afegir un fitxer a un Portafoli", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnMartiActionPerformed

    private void btnPolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolActionPerformed
        try {
            controlador.addAudio("/home/polg24/Desktop/did_it_again.mp3", "/home/polg24/Desktop/lil_teccasso.jpeg", "Sho", "08642", 45678);
            controlador.addAudio("/home/polg24/Desktop/these_days.mp3", "/home/polg24/Desktop/these_days.jpeg", "Sho", "08642", 45678);
            controlador.addAudio("/home/polg24/Desktop/hope.mp3", "/home/polg24/Desktop/x.jpg", "Sho", "08642", 45678);
            controlador.addAudio("/home/polg24/Desktop/did_it_again.mp3", "/home/polg24/Desktop/lil_teccasso.jpeg", "Uno otro", "08642", 45678);
            controlador.addAudio("/home/polg24/Desktop/these_days.mp3", "/home/polg24/Desktop/these_days.jpeg", "Bella chi", "08642", 45678);
            controlador.addAudio("/home/polg24/Desktop/hope.mp3", "/home/polg24/Desktop/x.jpg", "una verga salvahe", "08642", 45678);
            controlador.addImatge("/home/polg24/Desktop/Potato.jpg", "Sho", "un codec", 23, 45);
            controlador.addImatge("/home/polg24/Desktop/bolas.png", "una verga salvahe", "un codec", 23, 455678);
            
            
            updateLstRepositori();
            updateBtnPlayRepositori();

        }
        catch (ReproException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Error a l'afegir un fitxer a un Portafoli", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPolActionPerformed

    private void cmbPortafolisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPortafolisItemStateChanged
        updateLstPortafoli();
    }//GEN-LAST:event_cmbPortafolisItemStateChanged

    private void btnPlayFitxerRepositoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayFitxerRepositoriActionPerformed
        // TODO add your handling code here:
        try {
            controlador.playFitxer(lstRepositori.getSelectedIndex()+1);

        }
        catch (ReproException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Error al reproduir el fitxer", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_btnPlayFitxerRepositoriActionPerformed

    private void btnPlayRepositoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayRepositoriActionPerformed
        // TODO add your handling code here:
        try{
            controlador.playLlista();
        }
        catch(ReproException e){
            JOptionPane.showMessageDialog(this, e.toString(), "Error al reproduir", JOptionPane.ERROR_MESSAGE);

        }        
    }//GEN-LAST:event_btnPlayRepositoriActionPerformed

    private void btnEliminarFitxerPortafoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFitxerPortafoliActionPerformed
        // TODO add your handling code here:
        try {
            controlador.removeFitxer((String)cmbPortafolis.getSelectedItem(),lstPortafoli.getSelectedIndex());
        }
        catch (ReproException e) {
            JOptionPane.showMessageDialog(this, e.toString(), "Error a l'eliminar Portafoli", JOptionPane.ERROR_MESSAGE);
        }

        updateLstRepositori();
        updateLstPortafoli();        
    }//GEN-LAST:event_btnEliminarFitxerPortafoliActionPerformed

    private void lstPortafoliValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPortafoliValueChanged
        // TODO add your handling code here:
        updateBtnEliminarFitxerPortafoli();
    }//GEN-LAST:event_lstPortafoliValueChanged

    private void btnPlayPortafoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayPortafoliActionPerformed
        // TODO add your handling code here:
        try{
            controlador.playLlista((String)cmbPortafolis.getSelectedItem());
        }
        catch(ReproException e){
            JOptionPane.showMessageDialog(this, e.toString(), "Error al reproduir", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnPlayPortafoliActionPerformed

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // TODO add your handling code here:
        try{
            controlador.resumeReproduccio();
        }
        catch(ReproException e){
            JOptionPane.showMessageDialog(this, e.toString(), "Alerta", JOptionPane.WARNING_MESSAGE);            
        }        
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseActionPerformed
        // TODO add your handling code here:
        try{
            controlador.pauseReproduccio();
        }
        catch(ReproException e){
            JOptionPane.showMessageDialog(this, e.toString(), "Alerta", JOptionPane.WARNING_MESSAGE);            
        }        
    }//GEN-LAST:event_btnPauseActionPerformed

    private void btnAturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAturaActionPerformed
        // TODO add your handling code here:
        try{
            controlador.stopReproduccio();
        }
        catch(ReproException e){
            JOptionPane.showMessageDialog(this, e.toString(), "Alerta", JOptionPane.WARNING_MESSAGE);            
        }  
    }//GEN-LAST:event_btnAturaActionPerformed

    private void btnSaltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaltaActionPerformed
        // TODO add your handling code here:
        try{
            controlador.jumpReproduccio();
        }
        catch(ReproException e){
            JOptionPane.showMessageDialog(this, e.toString(), "Alerta", JOptionPane.WARNING_MESSAGE);            
        }  
    }//GEN-LAST:event_btnSaltaActionPerformed

    private void lstRepositoriComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lstRepositoriComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lstRepositoriComponentAdded

    private void chkCiclicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCiclicaActionPerformed
        // TODO add your handling code here:
        controlador.changeCiclica();
    }//GEN-LAST:event_chkCiclicaActionPerformed

    private void chkReverseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkReverseActionPerformed
        // TODO add your handling code here:
        controlador.changeReverse();
        
    }//GEN-LAST:event_chkReverseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplicacioUB4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplicacioUB4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfegirFitxerPortafoli;
    private javax.swing.JButton btnAfegirFitxerRepositori;
    private javax.swing.JButton btnAtura;
    private javax.swing.JButton btnCrearPortafoli;
    private javax.swing.JButton btnEliminarFitxerPortafoli;
    private javax.swing.JButton btnEliminarFitxerRepositori;
    private javax.swing.JButton btnEliminarPortafoli;
    private javax.swing.JButton btnGuardaDades;
    private javax.swing.JButton btnMarti;
    private javax.swing.JButton btnPause;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnPlayFitxerRepositori;
    private javax.swing.JButton btnPlayPortafoli;
    private javax.swing.JButton btnPlayRepositori;
    private javax.swing.JButton btnPol;
    private javax.swing.JButton btnRecuperaDades;
    private javax.swing.JButton btnSalta;
    private javax.swing.JCheckBox chkCiclica;
    private javax.swing.JCheckBox chkReverse;
    private javax.swing.JComboBox<String> cmbPortafolis;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSeleccionarPortafoli;
    private javax.swing.JLabel lblTitolPortafoli;
    private javax.swing.JList<String> lstPortafoli;
    private javax.swing.JList<String> lstRepositori;
    private javax.swing.JTextField txtTitolPortafoli;
    // End of variables declaration//GEN-END:variables
}
