/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ub.info.prog2.GabaldonPolMartinezMarti.vista;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import ub.info.prog2.GabaldonPolMartinezMarti.controlador.Controlador;
import ub.info.prog2.utils.ReproException;

/**
 *
 * @author marti
 */
public class FrmAfegirFitxerMultimedia2 extends javax.swing.JDialog {
    private Controlador controlador;
    /**
     * Creates new form FrmAfegirFitxerMultimedia2
     */
    public FrmAfegirFitxerMultimedia2(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        lblCami.setVisible(false);
        lblAutor.setVisible(false);
        lblCodec.setVisible(false);
        lblMultius1.setVisible(false);
        lblMultius2.setVisible(false);
        txtCami.setVisible(false);
        txtAutor.setVisible(false);
        txtCodec.setVisible(false);
        txtMultius1.setVisible(false);
        txtMultius2.setVisible(false);
        btnSelecciona1.setVisible(false);
        btnSelecciona2.setVisible(false);
        btnAcceptar.setVisible(false);
        btnAcceptar.setEnabled(false);
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTipusFitxer = new javax.swing.JComboBox<>();
        lblTipus = new javax.swing.JLabel();
        btnAfegir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAcceptar = new javax.swing.JButton();
        txtCami = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        txtCodec = new javax.swing.JTextField();
        txtMultius1 = new javax.swing.JTextField();
        txtMultius2 = new javax.swing.JTextField();
        lblCami = new javax.swing.JLabel();
        lblAutor = new javax.swing.JLabel();
        lblCodec = new javax.swing.JLabel();
        lblMultius1 = new javax.swing.JLabel();
        lblMultius2 = new javax.swing.JLabel();
        btnSelecciona1 = new javax.swing.JButton();
        btnSelecciona2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbTipusFitxer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imatge", "Audio" }));
        cmbTipusFitxer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipusFitxerActionPerformed(evt);
            }
        });

        lblTipus.setText("Tipus de fitxer a afegir:");

        btnAfegir.setText("Afegir");
        btnAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAcceptar.setText("Acceptar");
        btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarActionPerformed(evt);
            }
        });

        txtCami.setEditable(false);

        txtAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorActionPerformed(evt);
            }
        });
        txtAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAutorKeyReleased(evt);
            }
        });

        txtCodec.setEditable(false);
        txtCodec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodecActionPerformed(evt);
            }
        });

        txtMultius1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMultius1KeyReleased(evt);
            }
        });

        txtMultius2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMultius2ActionPerformed(evt);
            }
        });
        txtMultius2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMultius2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMultius2KeyReleased(evt);
            }
        });

        lblCami.setText("Cami fitxer");

        lblAutor.setText("Autor");

        lblCodec.setText("Codec");

        lblMultius1.setText("jLabel4");

        lblMultius2.setText("jLabel5");

        btnSelecciona1.setText("Selecciona");
        btnSelecciona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecciona1ActionPerformed(evt);
            }
        });

        btnSelecciona2.setText("Selecciona");
        btnSelecciona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecciona2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMultius1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCodec)
                                        .addComponent(lblMultius1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblMultius2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(54, 54, 54)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(txtMultius2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtCodec, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtAutor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCami, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblCami, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAutor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbTipusFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAfegir)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelecciona2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSelecciona1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(27, 27, 27)
                        .addComponent(btnAcceptar)))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTipus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipusFitxer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfegir))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCami)
                    .addComponent(txtCami, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecciona1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAutor)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodec)
                    .addComponent(txtCodec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMultius1)
                    .addComponent(txtMultius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelecciona2))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMultius2)
                    .addComponent(txtMultius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAcceptar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipusFitxerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipusFitxerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipusFitxerActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        //Tanca la finestra de dialeg
        this.dispose();        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtMultius2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMultius2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMultius2ActionPerformed

    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorActionPerformed

    private void btnSelecciona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecciona1ActionPerformed
        // TODO add your handling code here:
        File fitxer;
        //Creació del selector de fitxer
        JFileChooser seleccio = new JFileChooser();
        //Mostrem la finestra de dialeg
        //Resultat emmagazema una constant que indica si s’ha
        //seleccionat o no un fitxer
        int resultat = seleccio.showOpenDialog(this);
        //Assegurem que hi hagi un fitxer seleccionat
        if (resultat == JFileChooser.APPROVE_OPTION) {
        //Obtenim el fitxer
        fitxer=seleccio.getSelectedFile();
        //Posem la ruta del fitxer al quadre de text
        txtCami.setText(fitxer.toString());
        txtCodec.setText(fitxer.toString().substring(fitxer.toString().lastIndexOf(".")));
        }
        btnAcceptar.setEnabled( !(txtMultius1.getText().equals("") || txtMultius2.getText().equals("") || txtAutor.getText().equals("") || txtCami.getText().equals("")));
        
    }//GEN-LAST:event_btnSelecciona1ActionPerformed

    private void btnSelecciona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecciona2ActionPerformed
        // TODO add your handling code here:
        File fitxer;
        //Creació del selector de fitxer
        JFileChooser seleccio = new JFileChooser();
        //Mostrem la finestra de dialeg
        //Resultat emmagazema una constant que indica si s’ha
        //seleccionat o no un fitxer
        int resultat = seleccio.showOpenDialog(this);
        //Assegurem que hi hagi un fitxer seleccionat
        if (resultat == JFileChooser.APPROVE_OPTION) {
        //Obtenim el fitxer
        fitxer=seleccio.getSelectedFile();
        //Posem la ruta del fitxer al quadre de text
        txtMultius1.setText(fitxer.toString());
        }           
        btnAcceptar.setEnabled( !(txtMultius1.getText().equals("") || txtMultius2.getText().equals("") || txtAutor.getText().equals("") || txtCami.getText().equals("")));

    }//GEN-LAST:event_btnSelecciona2ActionPerformed

    private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarActionPerformed
        // TODO add your handling code here:
        //Tanca la finestra de dialeg
        try{
            if(((String)cmbTipusFitxer.getSelectedItem()).equals("Imatge")){
                controlador.addImatge(txtCami.getText(), txtAutor.getText(), txtCodec.getText(),Integer.parseInt(txtMultius1.getText()) , Integer.parseInt(txtMultius2.getText()));        
            }
            else{
                controlador.addAudio(txtCami.getText(), txtMultius1.getText(), txtAutor.getText(), txtCodec.getText(), Integer.parseInt(txtMultius2.getText()));
            }
            this.dispose();
        }
        catch(ReproException e){
            JOptionPane.showMessageDialog(this, e.toString(), "Error a l'afegir", JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btnAcceptarActionPerformed

    private void btnAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirActionPerformed
        // TODO add your handling code here:
        if(((String)cmbTipusFitxer.getSelectedItem()).equals("Imatge")){
            lblAutor.setVisible(true);
            lblCami.setVisible(true);
            lblCodec.setVisible(true);
            lblMultius1.setVisible(true);
            lblMultius2.setVisible(true);            
            lblMultius1.setText("Píxels alçada");
            lblMultius2.setText("Píxels amplada");
            txtAutor.setVisible(true);
            txtCami.setVisible(true);
            txtCodec.setVisible(true);
            txtMultius1.setVisible(true);
            txtMultius2.setVisible(true);
            txtAutor.setText("");
            txtCami.setText("");
            txtCodec.setText("");
            txtMultius1.setText("");
            txtMultius2.setText("");             
            txtMultius1.setEditable(true);
            btnSelecciona1.setVisible(true);
            btnSelecciona2.setVisible(false);
            btnAcceptar.setVisible(true);
        }
        else{
            lblAutor.setVisible(true);
            lblCami.setVisible(true);
            lblCodec.setVisible(true);
            lblMultius1.setVisible(true);
            lblMultius2.setVisible(true);            
            lblMultius1.setText("Camí imatge");
            lblMultius2.setText("Kbps");
            txtAutor.setVisible(true);
            txtCami.setVisible(true);
            txtCodec.setVisible(true);
            txtMultius1.setVisible(true);
            txtMultius2.setVisible(true); 
            txtAutor.setText("");
            txtCami.setText("");
            txtCodec.setText("");
            txtMultius1.setText("");
            txtMultius2.setText(""); 
            txtMultius1.setEditable(false);
            btnSelecciona1.setVisible(true);
            btnSelecciona2.setVisible(true);
            btnAcceptar.setVisible(true);
            
        }

    }//GEN-LAST:event_btnAfegirActionPerformed

    private void txtCodecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodecActionPerformed

    private void txtMultius2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultius2KeyPressed

    }//GEN-LAST:event_txtMultius2KeyPressed

    private void txtMultius2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultius2KeyReleased
        // TODO add your handling code here:
        String value = txtMultius2.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {

        } else {
           txtMultius2.setText("");
        }
        btnAcceptar.setEnabled( !(txtMultius1.getText().equals("") || txtMultius2.getText().equals("") || txtAutor.getText().equals("") || txtCami.getText().equals("")));
        
    }//GEN-LAST:event_txtMultius2KeyReleased

    private void txtMultius1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMultius1KeyReleased
        // TODO add your handling code here:
        String value = txtMultius1.getText();
        int l = value.length();
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {

        } else {
           txtMultius1.setText("");
        }
        btnAcceptar.setEnabled( !(txtMultius1.getText().equals("") || txtMultius2.getText().equals("") || txtAutor.getText().equals("") || txtCami.getText().equals("")));

    }//GEN-LAST:event_txtMultius1KeyReleased

    private void txtAutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutorKeyReleased
        // TODO add your handling code here:
        btnAcceptar.setEnabled( !(txtMultius1.getText().equals("") || txtMultius2.getText().equals("") || txtAutor.getText().equals("") || txtCami.getText().equals("")));
        
    }//GEN-LAST:event_txtAutorKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAfegirFitxerMultimedia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAfegirFitxerMultimedia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAfegirFitxerMultimedia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAfegirFitxerMultimedia2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Controlador controlador = new Controlador();
                FrmAfegirFitxerMultimedia2 dialog = new FrmAfegirFitxerMultimedia2(new javax.swing.JFrame(), true, controlador);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptar;
    private javax.swing.JButton btnAfegir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSelecciona1;
    private javax.swing.JButton btnSelecciona2;
    private javax.swing.JComboBox<String> cmbTipusFitxer;
    private javax.swing.JLabel lblAutor;
    private javax.swing.JLabel lblCami;
    private javax.swing.JLabel lblCodec;
    private javax.swing.JLabel lblMultius1;
    private javax.swing.JLabel lblMultius2;
    private javax.swing.JLabel lblTipus;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtCami;
    private javax.swing.JTextField txtCodec;
    private javax.swing.JTextField txtMultius1;
    private javax.swing.JTextField txtMultius2;
    // End of variables declaration//GEN-END:variables
}
